server:
  port: 8183
  servlet:
    context-path: /elastic-query-service

elastic-query-service:
  version: v1
  custom-audience: elastic-query-service


spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:28080/auth/realms/microservices-realm
          jwk-set-uri: http://localhost:28080/auth/realms/microservices-realm/protocol/openid-connect/certs
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public&binaryTransfer=true&reWriteBatchedInserts=true
    username: bereketfrezghi
    password: '{cipher}918d70c68eaa4d81bdc45ff462cdbcd010529482fdbe7f0624481632e3284742'
    driver-class-name: org.postgresql.Driver
    platform: postgres
    role: bereketfrezghi
    schema: classpath:init-schema.sql
    data: classpath:init-data.sql
    initialization-mode: always

elastic-query-config:
  text-field: text


elastic-config:
  index-name: twitter-index
  connection-url: http://localhost:9200
  connect-timeout-ms: 5000
  socket-timeout-ms: 30000

user-config:
  username: test
  password: '{cipher}0dd39d510f6980df9070e1629488045864bcec238cb1f58505638f9384a4a906'
  roles: USER

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

security:
  paths-to-ignore: /api-docs